### ISSUE TITLE
Error in Notion route test

### ISSUE THREAD

**Issue by shaiss** [shaiss/NotionPocket#1]
### **Description**

When running the test suite for the Notion route, an error is thrown with the message "TypeError: app.address is not a function". This error is preventing the test from properly executing and causing the test suite to fail.

### **Steps to reproduce**

1. Clone the repository to your local machine
2. Run **`npm install`** to install the necessary dependencies
3. Run **`npm test`** to execute the test suite

### **Expected outcome**

The test suite should run successfully and all tests should pass.

### **Actual outcome**

The test suite fails and the following error message is displayed:

```
  FAIL  test/notion.test.js
  ● Notion route › should return 200 OK and a success message

    TypeError: app.address is not a function

       5 |     it('should return 200 OK and a success message', async () => {
       6 |         const res = await request(app)
    >  7 |             .post('/notion')
         |              ^
       8 |             .send({
       9 |                 "save": {
      10 |                     "title": "Test Save",

```

### **Additional information**

This issue is related to the server listening on the same port as the test suite, causing a conflict. A solution could be to specify a different port for the test suite to use.

### **Tasks**

- [ ]  Investigate the cause of the error
- [ ]  Develop a solution to resolve the issue
- [ ]  Update the code and test suite accordingly
- [ ]  Test the changes to ensure the issue is resolved
